## Data Structure is Divided into two parts: 
- 1. Linear D.S. :Stack, Queue etc.
- 2. Non-linear Data Structrure : Tree, Graphs etc.

## Data structures can be broadly divided into four main categories:

1. `Primitive Data Structures`: These are the basic or fundamental data structures provided by a programming language. Examples include integers, floating-point numbers, characters, booleans, and pointers. These data types are typically built-in and are used to construct more complex data structures.

2. `Linear Data Structures`: In linear data structures, the data elements are organized sequentially or linearly. Each element has a unique predecessor and successor, except for the first and last elements. Some common linear data structures include arrays, linked lists, stacks, and queues.

3. `Non-linear Data Structures`: Unlike linear data structures, non-linear data structures do not follow a sequential or linear arrangement. The elements in these structures can be connected in multiple ways, forming a hierarchical or arbitrary relationship. Examples of non-linear data structures include trees, graphs, heaps, and hash tables.

4. `File Data Structures`: File data structures are used for organizing and storing data on secondary storage devices like hard drives. These structures are designed to optimize the storage and retrieval of data from files. Examples of file data structures include B-trees, indexes, and file allocation methods such as linked allocation or indexed allocation.

It's worth noting that these categories are not mutually exclusive, and data structures can often fall into multiple categories. Additionally, there are many variations and specialized data structures within each category that cater to specific requirements and optimizations

## Array 

An `array` is a fundamental data structure that stores a fixed-size sequence of elements of the same data type. It provides a way to represent and organize a collection of items in a contiguous block of memory. Each element in the array is identified by its index or position, starting from 0 for the first element.

`Arrays` can be one-dimensional or multi-dimensional, depending on the number of indices required to access an element. In a one-dimensional array, elements are arranged in a linear sequence. In a multi-dimensional array, elements are organized in a tabular form with rows and columns.

### The key characteristics of arrays include:

1. `Fixed Size`: The size of an array is predetermined and remains constant throughout its lifetime. Once created, the size cannot be dynamically changed.

2. `Homogeneous Elements`: An array can store elements of the same data type. For instance, an integer array can only store integers, a character array can only store characters, and so on.

3. `Random Access`: Elements in an array can be accessed directly by their index, allowing for constant-time access. This means that given an index, accessing the corresponding element in the array takes the same amount of time, regardless of the array's size.

Arrays are widely used in programming to store and manipulate collections of data efficiently. They provide a simple and effective way to manage and access elements, making them an essential tool in algorithm design and implementation.

## Array

Arrays can be classified into different types based on various characteristics. Here are a few common types of arrays:

1. `One-Dimensional Array`: Also known as a linear array, it is the simplest form of an array. It consists of a single row or sequence of elements. Each element can be accessed using a single index. For example, an array of integers [1, 2, 3, 4, 5] is a one-dimensional array.

2. `Two-Dimensional Array`: A two-dimensional array represents data in a tabular form with rows and columns. It is often used to represent matrices or grids. Elements in a two-dimensional array are accessed using two indices, one for the row and another for the column. For example, a 2D array representing a 3x3 matrix could be [[1, 2, 3], [4, 5, 6], [7, 8, 9]].

3. `Dynamic Array`: A dynamic array, also known as a resizable array or ArrayList, is an array-like data structure with a flexible size. It allows for dynamic resizing, meaning the array can grow or shrink as needed during runtime. Dynamic arrays are typically implemented using a combination of arrays and dynamic memory allocation.

4. `Static Array`: A static array refers to an array with a fixed size determined at compile-time. The size of a static array is typically specified when it is declared and cannot be changed during runtime. The memory for a static array is allocated at the time of declaration and is automatically managed by the system.

5. `Jagged Array`: A jagged array is an array of arrays, where each sub-array can have a different length. It is also known as a ragged array. This allows for irregular or uneven data structures. For example, a jagged array could be [[1, 2], [3, 4, 5], [6, 7, 8, 9]].

6. `Sparse Array`: A sparse array is an array where most of the elements have the default or empty value. It is optimized to efficiently store and access data with a significant number of default values. Sparse arrays are often used in situations where memory efficiency is crucial.

7. `Circular Array`: A circular array is an array that is treated as circular, meaning the last element is considered to be connected with the first element. It allows for efficient rotation or shifting operations without physically moving the elements.

These are just a few examples of array types. There are other variations and specialized array structures based on specific requirements and optimizations

### Explain working priciple of Dynanic Array

The working principle of a dynamic array involves dynamically allocating memory to accommodate a resizable array. Unlike static arrays, the size of a dynamic array can be adjusted during runtime to accommodate varying numbers of elements.

Here is a simplified explanation of the working principle of a dynamic array:

1. `Initialization`: Initially, a dynamic array is created with an initial capacity or size. This initial capacity can be chosen based on the anticipated number of elements or a default value.

2. `Memory Allocation`: The dynamic array starts with an allocated block of memory to hold the elements. The size of this initial memory block matches the initial capacity of the array.

3. `Insertion of Elements`: Elements can be added to the dynamic array as needed. If the array reaches its capacity while inserting a new element, it triggers a resizing operation.

4. `Resizing`: When the dynamic array needs more space to accommodate additional elements, it performs a resizing operation. This operation involves allocating a new, larger block of memory and copying the existing elements into the new memory block.

5. `Copying Elements`: During the resizing process, the existing elements are copied from the old memory block to the new one. This ensures that the order and integrity of the elements are maintained.

6. `Deallocation`: After copying the elements to the new memory block, the old memory block is deallocated to free up the memory previously occupied by the dynamic array.

7. `Updated Capacity`: The capacity of the dynamic array is updated to reflect the new size and memory allocation.

By dynamically resizing the array as needed, the dynamic array can accommodate a varying number of elements without wasting memory. This flexibility comes at the cost of occasional resizing operations, which can have a performance impact. However, the dynamic array allows for efficient insertion and deletion of elements compared to fixed-size static arrays.

It's important to note that the implementation details of dynamic arrays can vary depending on the programming language or data structure library being used. Common implementations include using pointers, memory reallocation functions, and tracking the capacity and size of the dynamic array.

## Implementation Data Structure

In [5]:
arr = [2, 1, 8, 9, 12, 15, 11, 19]

In [6]:
## Random Acess
arr[6]

11

In [10]:
## Search 15 return index possition.
## Suppose the searching elements is not present in an arrary, return -1
def linearSearch(arr, x):
    for i in range(len(arr)):
        if arr[i] == x:
            return i
    
    return -1



## Driver Code
arr = [2, 1, 8, 9, 12, 15, 11, 19]
x = 0
## Function Calling
result = linearSearch(arr, x)
print("Searching Element is present at the index", result)

Searching Element is present at the index -1


In [11]:
## Insert an elements 5 at index 2
## List.insert(index, elements)
arr.insert(2, 5)

In [13]:
arr

[2, 1, 5, 8, 9, 12, 15, 11, 19]

In [14]:
arr.remove(5)

In [15]:
arr

[2, 1, 8, 9, 12, 15, 11, 19]

In [16]:
arr.count(2)

1

In [18]:
arr.pop(1)

1

In [19]:
arr

[2, 8, 9, 12, 15, 11, 19]

In [22]:
## Sorting of Array
arr.sort()
arr

[2, 8, 9, 11, 12, 15, 19]

In [24]:
arr.index(9)

2

In [26]:
arr.reverse()

In [27]:
arr

[19, 15, 12, 11, 9, 8, 2]

## Address Of an elements in 2D Array

In a one-dimensional (1D) array, the elements are stored sequentially in memory, one after another. The elements of the array occupy contiguous memory locations. The storage of a 1D array in memory is typically straightforward and can be visualized as a linear block of memory

In [30]:
arr = [10, 20, 30, 40, 50]

## Address Of an elements in 2D Array

#### In what form 2D array are stored

In most programming languages, a two-dimensional (2D) array is typically stored in a contiguous block of memory using a row-major or column-major order.

1. `Row-Major Order`:
In row-major order, also known as row-wise order, the elements of each row are stored sequentially in memory. The rows themselves are stored consecutively, one after the other. This means that elements of the same row are adjacent in memory, while elements of different rows are stored further apa

In [28]:
A = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
A[1]

6

2. `Column-Major Order`:
In column-major order, also known as column-wise order, the elements of each column are stored sequentially in memory. The columns themselves are stored consecutively. This means that elements of the same column are adjacent in memory, while elements of different columns are stored further apart.

In [29]:
import numpy as np

# Create a 2D array using NumPy
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array to achieve column-major order
column_major_arr = np.transpose(arr)

# Print the column-major array
print(column_major_arr)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [31]:
## acess to located memmory address
## loc(a[i][j]) = base_memmory + [(j-l.b)n]+ [(i-l.b)m] v.i.z for column 

# Searching Concept in an Array

In [44]:
arr = [20, 40, 70, 10, 12, 11, 29, 75, 46]

In [51]:
## find index if
x = 11

In [50]:
def linear_search(arr, x):
    for i in range(len(arr)):
        if arr[i] == x:
            return i
    return "Element is not present"

In [52]:
linear_search(arr, x)

5

In [53]:
## Worst case scenario O(n): n
## best case scemario O(n): 1
## average case O(n) : 1+2+...+n/n : n(n+1)/2/n = n/2 = n

## Binary Search

`Binary search` is an efficient searching algorithm used to locate a specific element in a sorted array or list. It follows a divide-and-conquer approach by repeatedly dividing the search interval in half and narrowing down the search range until the desired element is found or determined to be absent.

#### Here is a step-by-step explanation of how binary search works:

1. Start with a sorted array or list. Binary search requires the elements to be arranged in ascending or descending order.

2. Set two pointers, start and end, initially pointing to the first and last elements of the array, respectively. These pointers define the current search interval.

3. Calculate the middle index of the search interval using the formula: mid = (start + end) // 2.

4. Compare the middle element with the target element being searched. There are three possibilities:

- If the middle element is equal to the target element, the search is successful, and the index of the middle element is returned.
- If the middle element is greater than the target element, the target element must be in the left half of the search interval. Adjust the end pointer to mid - 1 and go to step 3.
- If the middle element is less than the target element, the target element must be in the right half of the search interval. Adjust the start pointer to mid + 1 and go to step 3.
-. Repeat steps 3-4 until the target element is found, or the search interval is empty (start > end), indicating that the target element is not present in the array.

Binary search has a time complexity of O(log n), where n is the number of elements in the array. It is significantly faster than linear search for large sorted arrays.

In [54]:
def binary_search(arr, x):
    start = 0
    end = len(arr) - 1
    
    while start <= end:
        mid = (start + end) // 2
        
        # Check if x is present at the middle element
        if arr[mid] == x:
            return mid
        
        # If x is greater, ignore the left half
        elif arr[mid] < x:
            start = mid + 1
        
        # If x is smaller, ignore the right half
        else:
            end = mid - 1
    
    # Element is not present in the array
    return -1

# Example usage
arr = [10, 20, 30, 40, 50]
x = 30
result = binary_search(arr, x)

if result != -1:
    print("Element found at index", result)
else:
    print("Element is not present in the array")


Element found at index 2


In [7]:
def two_sum(nums, target):
    num_dict = {}  # Dictionary to store numbers and their indices
    
    # Traverse the array
    for i, num in enumerate(nums):
        complement = target - num
        
        # Check if the complement is already in the dictionary
        if complement in num_dict:
            return [num_dict[complement], i]  # Return the indices of the two numbers
        
        # Add the current number to the dictionary with its index
        num_dict[num] = i
    
    # No solution found
    return None

# Example usage
nums = [2, 7, 11, 15]
target = 9
result = two_sum(nums, target)

if result is not None:
    print("Output:", result)
else:
    print("No solution found")


Output: [0, 1]
